#include "LED_display.h"

void InitializeLEDDisplay(void) {
  SET_LED_DISPLAY_DRIVER_LATCH_AS_AN_OUTPUT;
  SET_LED_DISPLAY_DRIVER_BLANK_AS_AN_OUTPUT;
}

void SetLEDDisplay(unsigned char led) {
  SPISendByte(led);
  ENABLE_LED_DISPLAY_DRIVER_LATCH;
  DISABLE_LED_DISPLAY_DRIVER_LATCH;
  ENABLE_LED_DISPLAY_DRIVER_BLANK;
  DISABLE_LED_DISPLAY_DRIVER_BLANK;
}
